// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxXolvu9WTkYpnMqYxL-UuL-sHXFMDml8',
    appId: '1:251923529426:web:603e115df22db77dc6370b',
    messagingSenderId: '251923529426',
    projectId: 'nostracode-001',
    authDomain: 'nostracode-001.firebaseapp.com',
    storageBucket: 'nostracode-001.appspot.com',
    measurementId: 'G-PDS1TY67B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKTLSMkvGmGS1Ooo_ZRD7fYybZk3K1BR0',
    appId: '1:251923529426:android:b9920df8798d07e5c6370b',
    messagingSenderId: '251923529426',
    projectId: 'nostracode-001',
    storageBucket: 'nostracode-001.appspot.com',
  );
}
